services:
  yap2win:
    build: .
    image: "ghcr.io/cheng-chun-yuan/yap2win-bot"
    platform: linux/amd64
    environment:
      - TOKEN=${TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: python -m bot
    working_dir: /app/src